// Texte verbatim din designul aprobat (I18N), plus cateva siruri noi pentru stari reale (marcate in brief ca necesare).
export const I18N = {
  "en": {
    "navVilla": "The villa",
    "navLocation": "Location",
    "navGallery": "Gallery",
    "navReviews": "Reviews",
    "navCta": "Check availability",
    "heroKicker": "Roquebrune-Cap-Martin · Côte d'Azur · 5 min from Monaco",
    "heroSub": "A luxury villa 5 minutes from Monaco, with panoramic sea view, private pool and spa.",
    "aboutKicker": "About the villa",
    "aboutTitle": "The discreet refinement of the Côte d’Azur",
    "heroP1": "Just 5 minutes from Monaco, in the prestigious town of Roquebrune-Cap-Martin, this elegant villa embodies the discreet refinement of the Côte d'Azur. With a classic and sophisticated architecture, the white facade, ornamental railings and generous terraces create the image of a property with authentic Mediterranean charm.",
    "heroP2": "The lush vegetation and carefully landscaped gardens offer privacy and an exclusive atmosphere.",
    "aboutP3": "The villa is also fully secured and equipped for carefree stays: an alarm system, a safe, video surveillance around the property and a private garage. Every practical detail — from the landscaped gardens to the heated pool and the private spa with hammam — is looked after, so the house is ready to enjoy from the very first minute.",
    "amTitle": "Amenities & security",
    "am1": "Alarm system",
    "am2": "Safe",
    "am3": "Video surveillance",
    "am4": "Private garage",
    "am5": "Heated private pool",
    "am6": "Spa & hammam",
    "am7": "Sea-view terraces",
    "am8": "Landscaped gardens",
    "btnBook": "Book your stay",
    "btnGallery": "View the gallery",
    "tag1": "5 min from Monaco",
    "tag2": "Sea view",
    "tag3": "Private pool",
    "tag4": "Spa & hammam",
    "tag5": "French elegance",
    "stat1": "From Monaco and Monte-Carlo",
    "stat2": "Mediterranean sea view",
    "stat3": "Guest rating",
    "stat4": "Private hammam & pool",
    "villaKicker": "The villa",
    "f1Title": "Panoramic sea view",
    "f1Copy": "One of the most spectacular assets of the villa is the view of the Mediterranean Sea, which can be admired directly from the rooms. The master bedroom opens onto a terrace with panoramic views, offering mornings bathed in light and the perfect setting to enjoy coffee in peace.",
    "f2Title": "French Riviera interiors",
    "f2Copy": "The interiors combine classic French elegance with contemporary comfort: refined furniture, crystal chandeliers, delicate textiles, wooden parquet and carefully chosen decorative details. Pastel tones create a warm, bright and feminine atmosphere, in perfect harmony with the spirit of the Riviera.",
    "f3Title": "Private spa & hammam",
    "f3Copy": "The property also features a private spa with hammam, ideal for moments of relaxation and wellness in the privacy of your own residence.",
    "locKicker": "Location — 5 minutes from Monaco",
    "locTitle": "An exclusive retreat between Monaco and the Mediterranean",
    "locCopy": "The location of the villa is exceptional: Monaco is a few minutes away, the beaches and prestigious ports of the Riviera are nearby, and Roquebrune-Cap-Martin offers that rare feeling of privacy, elegance and Mediterranean authenticity.",
    "locCopy2": "It is more than a villa - it is a lifestyle.",
    "galKicker": "Gallery",
    "cap1": "Master bedroom",
    "cap2": "The private pool",
    "cap3": "The terrace",
    "cap4": "The salon",
    "cap5": "The hammam",
    "cap6": "The gardens",
    "cap7": "Guest bedroom",
    "cap8": "Marble bathroom",
    "cap9": "The kitchen",
    "cap10": "Sitting room",
    "cap11": "The library",
    "cap12": "The entrance hall",
    "cap13": "Blue bedroom",
    "capD1": "Opens onto the panoramic terrace — the sea from the bed.",
    "capD2": "Heated pool along the balustraded terrace, framed by palms.",
    "capD7": "Calm pastel tones and soft garden light.",
    "capD8": "Marble walls, corner bath and wrought-iron windows.",
    "capD9": "Provençal kitchen opening onto the garden terrace.",
    "capD10": "A quiet salon opening onto the lawn.",
    "capD11": "Reading corner with fitted bookcases.",
    "capD12": "Oak-panelled hall and the original staircase.",
    "capD13": "Bright guest room in Riviera blue.",
    "revKicker": "Guest reviews",
    "revSummary": "Average rating",
    "rev1": "The sea view from the master terrace is exactly what the photos promise. Coffee at sunrise, Monaco in five minutes, and complete quiet in the evening. The most relaxing week we have had in years.",
    "rev1By": "— Isabelle & Marc, Paris · July 2026",
    "rev2": "Elegant, immaculate and wonderfully private. The hammam and pool made it feel like a boutique hotel, but with the freedom of your own villa. Perfect base for the Grand Prix weekend.",
    "rev2By": "— James R., London · May 2026",
    "rev3": "A beautiful classic villa with real character — chandeliers, parquet, gardens full of flowers. Ten minutes to the beach at Cap-Martin. We are already planning to return next summer.",
    "rev3By": "— Familie Weber, München · August 2026",
    "rateNow": "Rate your stay:",
    "revGateNote": "Only guests who have completed a paid stay at Villa Les Mouettes can leave a review. Enter the email address used for your reservation — we will send a one-time link to it.",
    "revEmailLabel": "Reservation email address",
    "revVerifyBtn": "Email me the link",
    "revVerifyErr": "This email address is not linked to any reservation. Please use the exact address from your booking confirmation.",
    "revVerifiedOk": "Verified guest",
    "revLeave": "Leave a review",
    "revFormTitle": "Share your experience at Villa Les Mouettes",
    "revStarsLabel": "Your rating",
    "revTextLabel": "Your review",
    "revTextPh": "What did you enjoy most?",
    "revSubmit": "Publish review",
    "revThanks": "Thank you — your review has been published below.",
    "revStayed": "Guest",
    "emailFlowTitle": "What happens next",
    "emailFlow1": "A confirmation email is sent to you as proof of your reservation request.",
    "emailFlow2": "The owner is notified instantly by email with your dates and details.",
    "emailFlow3": "A few minutes after payment is received, the invoice is emailed to you automatically.",
    "emailSendBtn": "Send confirmation by email",
    "payTrust": "Secure payment via Stripe · 3D Secure",
    "payBtn": "Pay securely with Stripe",
    "emailFlowPay": "You are redirected to Stripe to complete your payment securely (3D Secure verified).",
    "bookKicker": "Availability & booking",
    "bookTitle": "Check availability and book direct",
    "earlier": "← Earlier",
    "later": "Later →",
    "legendSelected": "Selected",
    "legendBooked": "Booked",
    "legendAvailable": "Available",
    "fArrival": "Arrival",
    "fDeparture": "Departure",
    "fSelect": "Select on calendar",
    "fAdults": "Adults",
    "fChildren": "Children",
    "fName": "Full name",
    "fNamePh": "Your name",
    "fEmail": "Email address",
    "fNotes": "Notes",
    "fNotesPh": "Anything we should know",
    "fSubmit": "Send reservation request",
    "fNote": "Book direct for the best rates. Our concierge will confirm availability and personalise your stay within 24 hours.",
    "thanksTitle": "Thank you for your enquiry.",
    "confirm1": "Your request for ",
    "confirm2": " to ",
    "confirm3": " has been received. A member of our team will be in touch within 24 hours to confirm your reservation at Villa Les Mouettes.",
    "again": "Make another enquiry",
    "errDates": "Please select arrival and departure dates on the calendar.",
    "errFields": "Please fill in your name and a valid email address.",
    "navContact": "Contact",
    "conKicker": "Contact",
    "conTitle": "Speak directly with the owner",
    "conCopy": "For availability, rates and personalised stays, contact the owner directly — the fastest answer is on WhatsApp, usually within the hour.",
    "conWhatsapp": "WhatsApp the owner",
    "conCall": "Call",
    "conAddrLabel": "Address",
    "conAddrNote": "Click the address or the map to open the exact location in Google Maps.",
    "conMapCta": "Open in Google Maps",
    "quote": "A privileged address on the Côte d'Azur, where luxury is not ostentatious, but is expressed through views, architecture, tranquility and refinement.",
    "closeTitle": "It is more than a villa - it is a lifestyle.",
    "footer": "Villa Les Mouettes — luxury villa rental near Monaco · Roquebrune-Cap-Martin • Côte d'Azur • 5 min from Monaco • Sea view • Private pool • Private spa • French elegance",
    "revLinkSent": "If this address matches a completed stay, a review link is on its way (valid 7 days). Check your inbox.",
    "revTokenBad": "This review link is invalid or has expired. Request a new one from the Reviews section.",
    "payOff": "Online payment is not enabled yet — the owner will confirm your request and send payment instructions.",
    "emailsNotSent": "Email delivery is not enabled yet: you will not receive an automatic confirmation. The owner will reply directly.",
    "back": "Back to the villa",
    "locale": "en-GB",
    "dows": [
      "Mo",
      "Tu",
      "We",
      "Th",
      "Fr",
      "Sa",
      "Su"
    ],
    "revPending": "Thank you — your review has been received and will appear once the owner approves it.",
    "revUnavailable": "Review verification is not configured yet. Please contact the owner.",
    "demo": "DEMO",
    "demoBooked": "Sample availability pattern, not the real calendar.",
    "demoReviews": "Sample reviews — not from real guests.",
    "errServer": "The request could not be saved. Please try again or contact the owner.",
    "errRange": "The selected stay includes dates that are already booked.",
    "loadingCal": "Loading availability…",
    "sending": "Sending…"
  },
  "fr": {
    "navVilla": "La villa",
    "navLocation": "Emplacement",
    "navGallery": "Galerie",
    "navReviews": "Avis",
    "navCta": "Voir les disponibilités",
    "heroKicker": "Roquebrune-Cap-Martin · Côte d'Azur · 5 min de Monaco",
    "heroSub": "Une villa de luxe à 5 minutes de Monaco, avec vue mer panoramique, piscine privée et spa.",
    "aboutKicker": "À propos de la villa",
    "aboutTitle": "Le raffinement discret de la Côte d'Azur",
    "heroP1": "À seulement 5 minutes de Monaco, dans la prestigieuse commune de Roquebrune-Cap-Martin, cette élégante villa incarne le raffinement discret de la Côte d'Azur. Avec une architecture classique et sophistiquée, la façade blanche, les balustrades ornementales et les généreuses terrasses composent l'image d'une propriété au charme méditerranéen authentique.",
    "heroP2": "La végétation luxuriante et les jardins soigneusement paysagés offrent intimité et atmosphère exclusive.",
    "aboutP3": "La villa est également entièrement sécurisée et équipée pour des séjours en toute sérénité : système d'alarme, coffre-fort, vidéosurveillance autour de la propriété et garage privé. Chaque détail pratique — des jardins paysagés à la piscine chauffée et au spa privé avec hammam — est soigné, pour que la maison se vive dès la première minute.",
    "amTitle": "Équipements & sécurité",
    "am1": "Système d'alarme",
    "am2": "Coffre-fort",
    "am3": "Vidéosurveillance",
    "am4": "Garage privé",
    "am5": "Piscine privée chauffée",
    "am6": "Spa & hammam",
    "am7": "Terrasses vue mer",
    "am8": "Jardins paysagés",
    "btnBook": "Réserver votre séjour",
    "btnGallery": "Voir la galerie",
    "tag1": "5 min de Monaco",
    "tag2": "Vue mer",
    "tag3": "Piscine privée",
    "tag4": "Spa & hammam",
    "tag5": "Élégance française",
    "stat1": "De Monaco et Monte-Carlo",
    "stat2": "Vue mer Méditerranée",
    "stat3": "Note des hôtes",
    "stat4": "Hammam & piscine privés",
    "villaKicker": "La villa",
    "f1Title": "Vue mer panoramique",
    "f1Copy": "L'un des atouts les plus spectaculaires de la villa est la vue sur la mer Méditerranée, que l'on peut admirer directement depuis les chambres. La chambre principale s'ouvre sur une terrasse à la vue panoramique, offrant des matinées baignées de lumière et le cadre parfait pour savourer un café en toute tranquillité.",
    "f2Title": "Intérieurs Riviera française",
    "f2Copy": "Les intérieurs allient l'élégance classique française au confort contemporain : mobilier raffiné, lustres en cristal, textiles délicats, parquet en bois et détails décoratifs soigneusement choisis. Les tons pastel créent une atmosphère chaleureuse, lumineuse et féminine, en parfaite harmonie avec l'esprit de la Riviera.",
    "f3Title": "Spa privé & hammam",
    "f3Copy": "La propriété dispose également d'un spa privé avec hammam, idéal pour des moments de détente et de bien-être dans l'intimité de votre résidence.",
    "locKicker": "Emplacement — à 5 minutes de Monaco",
    "locTitle": "Une retraite exclusive entre Monaco et la Méditerranée",
    "locCopy": "L'emplacement de la villa est exceptionnel : Monaco est à quelques minutes, les plages et les ports prestigieux de la Riviera sont à proximité, et Roquebrune-Cap-Martin offre ce rare sentiment d'intimité, d'élégance et d'authenticité méditerranéenne.",
    "locCopy2": "C'est plus qu'une villa - c'est un art de vivre.",
    "galKicker": "Galerie",
    "cap1": "Chambre principale",
    "cap2": "La piscine privée",
    "cap3": "La terrasse",
    "cap4": "Le salon",
    "cap5": "Le hammam",
    "cap6": "Les jardins",
    "cap7": "Chambre d'amis",
    "cap8": "Salle de bain en marbre",
    "cap9": "La cuisine",
    "cap10": "Petit salon",
    "cap11": "La bibliothèque",
    "cap12": "Le hall d'entrée",
    "cap13": "Chambre bleue",
    "capD1": "S'ouvre sur la terrasse panoramique — la mer depuis le lit.",
    "capD2": "Piscine chauffée le long de la terrasse à balustres, entourée de palmiers.",
    "capD7": "Tons pastel apaisants et douce lumière du jardin.",
    "capD8": "Murs en marbre, baignoire d’angle et fenêtres en fer forgé.",
    "capD9": "Cuisine provençale ouverte sur la terrasse du jardin.",
    "capD10": "Un salon paisible ouvert sur la pelouse.",
    "capD11": "Coin lecture avec bibliothèques intégrées.",
    "capD12": "Hall lambrissé de chêne et escalier d’origine.",
    "capD13": "Chambre d’amis lumineuse en bleu Riviera.",
    "revKicker": "Avis des hôtes",
    "revSummary": "Note moyenne",
    "rev1": "La vue mer depuis la terrasse de la chambre principale est exactement ce que promettent les photos. Café au lever du soleil, Monaco en cinq minutes, et un calme absolu le soir. La semaine la plus reposante que nous ayons passée depuis des années.",
    "rev1By": "— Isabelle & Marc, Paris · juillet 2026",
    "rev2": "Élégante, impeccable et merveilleusement privée. Le hammam et la piscine donnent l'impression d'un hôtel de charme, avec la liberté de sa propre villa. Base parfaite pour le week-end du Grand Prix.",
    "rev2By": "— James R., Londres · mai 2026",
    "rev3": "Une belle villa classique avec un vrai caractère — lustres, parquet, jardins fleuris. Dix minutes de la plage du Cap-Martin. Nous prévoyons déjà de revenir l'été prochain.",
    "rev3By": "— Famille Weber, Munich · août 2026",
    "rateNow": "Notez votre séjour :",
    "revGateNote": "Seuls les hôtes ayant effectué un séjour payé à la Villa Les Mouettes peuvent laisser un avis. Saisissez l'adresse e-mail utilisée pour votre réservation — nous y enverrons un lien à usage unique.",
    "revEmailLabel": "E-mail de la réservation",
    "revVerifyBtn": "Envoyez-moi le lien",
    "revVerifyErr": "Cette adresse e-mail n'est liée à aucune réservation. Utilisez l'adresse exacte de votre confirmation de réservation.",
    "revVerifiedOk": "Hôte vérifié",
    "revLeave": "Laisser un avis",
    "revFormTitle": "Partagez votre expérience à la Villa Les Mouettes",
    "revStarsLabel": "Votre note",
    "revTextLabel": "Votre avis",
    "revTextPh": "Qu'avez-vous préféré ?",
    "revSubmit": "Publier l'avis",
    "revThanks": "Merci — votre avis a été publié ci-dessous.",
    "revStayed": "Hôte",
    "emailFlowTitle": "La suite",
    "emailFlow1": "Un e-mail de confirmation vous est envoyé comme preuve de votre demande de réservation.",
    "emailFlow2": "Le propriétaire est notifié instantanément par e-mail avec vos dates et coordonnées.",
    "emailFlow3": "Quelques minutes après réception du paiement, la facture vous est envoyée automatiquement par e-mail.",
    "emailSendBtn": "Envoyer la confirmation par e-mail",
    "payTrust": "Paiement sécurisé via Stripe · 3D Secure",
    "payBtn": "Payer en toute sécurité avec Stripe",
    "emailFlowPay": "Vous êtes redirigé vers Stripe pour finaliser votre paiement en toute sécurité (vérification 3D Secure).",
    "bookKicker": "Disponibilités & réservation",
    "bookTitle": "Vérifiez les disponibilités et réservez en direct",
    "earlier": "← Précédent",
    "later": "Suivant →",
    "legendSelected": "Sélectionné",
    "legendBooked": "Réservé",
    "legendAvailable": "Disponible",
    "fArrival": "Arrivée",
    "fDeparture": "Départ",
    "fSelect": "Choisir sur le calendrier",
    "fAdults": "Adultes",
    "fChildren": "Enfants",
    "fName": "Nom complet",
    "fNamePh": "Votre nom",
    "fEmail": "Adresse e-mail",
    "fNotes": "Remarques",
    "fNotesPh": "Ce que nous devrions savoir",
    "fSubmit": "Envoyer la demande de réservation",
    "fNote": "Réservez en direct pour les meilleurs tarifs. Notre conciergerie confirmera la disponibilité et personnalisera votre séjour sous 24 heures.",
    "thanksTitle": "Merci pour votre demande.",
    "confirm1": "Votre demande du ",
    "confirm2": " au ",
    "confirm3": " a bien été reçue. Un membre de notre équipe vous contactera sous 24 heures pour confirmer votre réservation à la Villa Les Mouettes.",
    "again": "Faire une autre demande",
    "errDates": "Veuillez sélectionner les dates d'arrivée et de départ sur le calendrier.",
    "errFields": "Veuillez renseigner votre nom et une adresse e-mail valide.",
    "navContact": "Contact",
    "conKicker": "Contact",
    "conTitle": "Contactez directement le propriétaire",
    "conCopy": "Pour les disponibilités, les tarifs et les séjours personnalisés, contactez directement le propriétaire — la réponse la plus rapide est sur WhatsApp, généralement dans l'heure.",
    "conWhatsapp": "WhatsApp le propriétaire",
    "conCall": "Appeler",
    "conAddrLabel": "Adresse",
    "conAddrNote": "Cliquez sur l'adresse ou sur la carte pour ouvrir l'emplacement exact dans Google Maps.",
    "conMapCta": "Ouvrir dans Google Maps",
    "quote": "Une adresse privilégiée sur la Côte d'Azur, où le luxe n'est pas ostentatoire, mais s'exprime par les vues, l'architecture, la tranquillité et le raffinement.",
    "closeTitle": "C'est plus qu'une villa - c'est un art de vivre.",
    "footer": "Villa Les Mouettes — location de villa de luxe près de Monaco · Roquebrune-Cap-Martin • Côte d'Azur • 5 min de Monaco • Vue mer • Piscine privée • Spa privé • Élégance française",
    "revLinkSent": "Si cette adresse correspond à un séjour terminé, un lien pour laisser un avis est en route (valable 7 jours). Vérifiez votre boîte mail.",
    "revTokenBad": "Ce lien d'avis est invalide ou expiré. Demandez-en un nouveau depuis la section Avis.",
    "payOff": "Le paiement en ligne n'est pas encore activé — le propriétaire confirmera votre demande et vous enverra les instructions de paiement.",
    "emailsNotSent": "L'envoi d'e-mails n'est pas encore activé : vous ne recevrez pas de confirmation automatique. Le propriétaire vous répondra directement.",
    "back": "Retour à la villa",
    "locale": "fr-FR",
    "dows": [
      "Lu",
      "Ma",
      "Me",
      "Je",
      "Ve",
      "Sa",
      "Di"
    ],
    "revPending": "Merci — votre avis a bien été reçu et apparaîtra après validation par le propriétaire.",
    "revUnavailable": "La vérification des avis n’est pas encore configurée. Veuillez contacter le propriétaire.",
    "demo": "DÉMO",
    "demoBooked": "Disponibilités d’exemple, pas le vrai calendrier.",
    "demoReviews": "Avis d’exemple — pas de vrais hôtes.",
    "errServer": "La demande n’a pas pu être enregistrée. Réessayez ou contactez le propriétaire.",
    "errRange": "Le séjour choisi comprend des dates déjà réservées.",
    "loadingCal": "Chargement des disponibilités…",
    "sending": "Envoi…"
  }
} as const;

export type Lang = keyof typeof I18N;
export type Copy = (typeof I18N)[Lang];
export const LANGS: Lang[] = ["en", "fr"];
